//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolito_4am_DB
{


    public partial class _Default
    {
        protected global::System.Web.UI.WebControls.Label lblCantidadUsuarios;
        
        /// <summary>
        /// Control rptProductos.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptProductos;
    }
}
