//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Monolito_4am_DB
{


    public partial class SiteMaster
    {

        /// <summary>
        /// Control HeadContent.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder HeadContent;

        /// <summary>
        /// Control MainContent.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
        
        protected global::System.Web.UI.WebControls.PlaceHolder phAdmin;
        protected global::System.Web.UI.WebControls.PlaceHolder phUsuario;
        protected global::System.Web.UI.WebControls.LinkButton btnCerrarSesion;
        protected global::System.Web.UI.WebControls.Image imgPerfilSidebar;
        protected global::System.Web.UI.WebControls.HyperLink lnkNombreUsuario;
    }
}
